import { Navigation } from "./components/Navigation.jsx";

export const metadata = {
  title: "First app with next js 13",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
