export const metadata = {
  title: "First app with next js 13",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <ul>
              <li>Home</li>
              <li>Prueba</li>
              <li>Test</li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
